### ISSUE TITLE
net-im/tg_owt: fails to build — CMAKE_SYSTEM_NAME check misses MidnightBSD

### ISSUE THREAD

**Issue by laffer1** [MidnightBSD/mports#854]
`net-im/tg_owt` fails to build on MidnightBSD 4.2 amd64, which also blocks
`net-im/telegram-desktop`.

## Error

```
src/rtc_base/byte_order.h:98:2: error: "Missing byte order functions for this arch."
```

## Root cause

`cmake/libwebrtcbuild.cmake:99` gates the BSD define on an exact match:

```cmake
    elseif (CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
        target_compile_definitions(libwebrtcbuild
        INTERFACE
            WEBRTC_FREEBSD
        )
```

On MidnightBSD `CMAKE_SYSTEM_NAME` is `"MidnightBSD"`, so `WEBRTC_FREEBSD` is
never defined. `src/rtc_base/byte_order.h` then falls through:

```c
#elif defined(WEBRTC_FREEBSD) || defined(WEBRTC_OPENBSD)
#include <sys/endian.h>
#else
#error "Missing byte order functions for this arch."
```

## Suggested fix

Patch `cmake/libwebrtcbuild.cmake` to accept MidnightBSD alongside FreeBSD,
e.g. `elseif (CMAKE_SYSTEM_NAME MATCHES "^(FreeBSD|MidnightBSD)$")`.

MidnightBSD does define `__FreeBSD__` at the C preprocessor level, so only the
CMake-level string comparison needs changing.

## Note

This is the same class of bug fixed in #850 for `devel/cmake-core`. Any port
testing `CMAKE_SYSTEM_NAME` against `"FreeBSD"` is silently false here. Grep
for it when porting:

```sh
grep -rn 'FreeBSD' --include='*.cmake' --include='CMakeLists.txt' .
```

Found while verifying consumers for the fmt 12 update (#853); unrelated to
that change.
