### ISSUE TITLE
games/devilutionX: fails to build — 'isascii' undeclared in base libc++ <__locale>

### ISSUE THREAD

**Issue by laffer1** [MidnightBSD/mports#858]
`games/devilutionX` 1.5.4 fails to build on MidnightBSD 4.2 amd64.

## Error

```
In file included from /usr/include/c++/v1/vector:325:
In file included from /usr/include/c++/v1/__format/formatter_bool.h:19:
In file included from /usr/include/c++/v1/__format/formatter_integral.h:35:
/usr/include/c++/v1/__locale:530:12: error: use of undeclared identifier 'isascii'
  530 |     return isascii(__c) ? (__tab_[static_cast<int>(__c)] & __m) != 0 : false;
      |            ^
/usr/include/c++/v1/__locale:535:16: error: use of undeclared identifier 'isascii'
/usr/include/c++/v1/__locale:541:11: error: use of undeclared identifier 'isascii'
/usr/include/c++/v1/__locale:548:12: error: use of undeclared identifier 'isascii'
```

## Root cause

This is in the **base system** libc++ headers, not in devilutionX. Including
`<vector>` pulls in `__format/formatter_bool.h` -> `__format/formatter_integral.h`
-> `__locale`, and `__locale` uses `isascii()` without it being declared.

`isascii()` is not a standard C function; on FreeBSD/MidnightBSD it is exposed
by `<ctype.h>` only under `__BSD_VISIBLE` (or `__XSI_VISIBLE`). Something in
the include path is causing `<ctype.h>` to be included with those guards
disabled — building with `-std=c++20` (as devilutionX does) can select a
strict POSIX visibility level.

## Notes

- The port builds with `-std=c++20 -flto=thin`.
- The trigger is `<vector>` reaching `__locale` through the `<format>` headers,
  so any C++20 port that includes `<vector>` may be exposed.

This likely needs a base-system fix rather than a port patch, but filing here
since it blocks a port. A local workaround might be forcing `__BSD_VISIBLE`,
though that is papering over the header bug.

Found while verifying consumers for the fmt 12 update (#853). devilutionX only
receives a PORTREVISION bump there; the failure is in system headers and
unrelated to fmt.
